net-snmp: replace borked patch to fix compilation
net-snmp got a broken patch that does not apply, causing the build to
break:

    ERROR: net-snmp-5.9.3-r0 do_patch: Applying patch '0001-unload_all_mibs-fix-memory-leak-by-freeing-tclist.patch' on target directory '.../work/cortexa9-vfp-poky-linux-gnueabi/net-snmp/5.9.3-r0/net-snmp-5.9.3'
    CmdError('quilt --quiltrc .../work/cortexa9-vfp-poky-linux-gnueabi/net-snmp/5.9.3-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-unload_all_mibs-fix-memory-leak-by-freeing-tclist.patch
    patching file snmplib/parse.c
    Hunk #1 FAILED at 28.
    Hunk #2 succeeded at 4225 (offset 10 lines).
    1 out of 2 hunks FAILED -- rejects in file snmplib/parse.c
    Patch 0001-unload_all_mibs-fix-memory-leak-by-freeing-tclist.patch does not apply (enforce with -f)

    stderr: ')

Fix this by providing our own version of the patch that works, fixing
the build again.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>
(cherry picked from commit 8d06b326b4d877fad209bd7c4ada35cd2c4ea72c)
Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>