python3-ryu: switch to setuptools3_legacy
setuptools3 was recently switch from setup.py to wheels, but the
latter won't work when non-python files get created (like python3-ryu
does).

So switch it back to setup.py by switching to setuptools3_legacy.

Fixes the following build error due to ryu.conf being put into the wrong
directory:

ERROR: python3-ryu-4.34+gitAUTOINC+c776e4cb68-r1 do_package: QA Issue: python3-ryu: Files/directories were installed but not shipped in any package:
  /usr/etc
  /usr/etc/ryu
  /usr/etc/ryu/ryu.conf
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
python3-ryu: 3 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>