python3-ryu: add support for newer eventlet versions
Newer eventlet versions moved ALREADY_HANDLED, which causes the import
to fail. So backport a commit from upstream ryu that handles both old
and new way.

Fix the following runtime error:

Traceback (most recent call last):
  File "/usr/bin/ryu-manager", line 33, in <module>
    sys.exit(load_entry_point('ryu==4.34', 'console_scripts', 'ryu-manager')())
  File "/usr/bin/ryu-manager", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/ryu/cmd/manager.py", line 33, in <module>
    from ryu.app import wsgi
  File "/usr/lib/python3.10/site-packages/ryu/app/wsgi.py", line 109, in <module>
    class _AlreadyHandledResponse(Response):
  File "/usr/lib/python3.10/site-packages/ryu/app/wsgi.py", line 112, in _AlreadyHandledResponse
    from eventlet.wsgi import ALREADY_HANDLED
ImportError: cannot import name 'ALREADY_HANDLED' from 'eventlet.wsgi' (/usr/lib/python3.10/site-packages/eventlet/wsgi.py)

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>