ryu: fix syntax error in ofctl_v1_3.py
Syntax errors such as the one fixed by this commit are not caught by
setuptools [1]. It was only visible in bitbake's log.do_install:

    File "/usr/lib/python3.8/site-packages/ryu/lib/ofctl_v1_3.py", line 244
      'ofdpa_mpls_l2_port': str_to_int,
      ^
  SyntaxError: invalid syntax

None of our tests failed due to this error. It would have been caught
earlier had the code been checked with pylint before having git create
the patch series.

[1] https://github.com/pypa/setuptools/issues/1637

Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>