images/full: change python2-ofdpa -> python3-ofdpa
With the update of of-dpa to python3, the python2-ofdpa package is
renamed to python3-ofdpa.

When switching meta-ofdpa to the version containing said update, we
need to update the package name here in order to avoid this error:

ERROR: Nothing RPROVIDES 'python2-ofdpa' (but /home/builder/poky/meta-switch/recipes-core/images/full.bb RDEPENDS on or otherwise requires it)

This change and the one in meta-ofdpa depend on each other and should be
activated at the same time.

Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>