frr: fix error handling in generate_support_bundle.py
Before we can write or print the output of errors, we need to convert it
to strings.

Fixes the following error on errors:

  File "/usr/lib/frr/generate_support_bundle.py", line 55, in executeCommand
    cmd_output = subprocess.check_output(cmd_exec_str, shell=True)
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'vtysh -c "show zebra fpm stats" ' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/frr/generate_support_bundle.py", line 117, in <module>
    processConfFile()
  File "/usr/lib/frr/generate_support_bundle.py", line 113, in processConfFile
    executeCommand(cmd_line[0], outputFile)
  File "/usr/lib/frr/generate_support_bundle.py", line 69, in executeCommand
    outputFile.write(e.output)
TypeError: write() argument must be str, not bytes

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>