python3-eventlet: update to 0.37.0
Something is broken in scarthgap's python3-eventlet 0.36.1, causing
errors on startup of ryu:

Jun 25 13:30:19 accton-as4610-54 systemd[1]: Started ryu-manager.
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]: Traceback (most recent call last):
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:   File "/usr/bin/ryu-manager", line 6, in <module>
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:     from ryu.cmd.manager import main
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:   File "/usr/lib/python3.12/site-packages/ryu/cmd/manager.py", line 22, in <module>
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:     from ryu.lib import hub
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:   File "/usr/lib/python3.12/site-packages/ryu/lib/hub.py", line 30, in <module>
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:     import eventlet
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:   File "/usr/lib/python3.12/site-packages/eventlet/__init__.py", line 6, in <module>
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:     from eventlet import convenience
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:   File "/usr/lib/python3.12/site-packages/eventlet/convenience.py", line 4, in <module>
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:     from eventlet import greenpool
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:   File "/usr/lib/python3.12/site-packages/eventlet/greenpool.py", line 4, in <module>
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:     from eventlet import queue
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:   File "/usr/lib/python3.12/site-packages/eventlet/queue.py", line 48, in <module>
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:     from eventlet.event import Event
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:   File "/usr/lib/python3.12/site-packages/eventlet/event.py", line 1, in <module>
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]:     from eventlet import hubs
Jun 25 13:30:20 accton-as4610-54 ryu-manager[2594]: ImportError: cannot import name 'hubs' from partially initialized module 'eventlet' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/eventlet/__init__.py)
Jun 25 13:30:20 accton-as4610-54 systemd[1]: ryu-manager.service: Main process exited, code=exited, status=1/FAILURE

Fix this by updating eventlet to 0.37.0, which seems to fix the issue.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>