Revert "distro: ensure license texts are available on device"
It looks like at least kirkstone does not properly generate license info
for bin-packages, breaking building images from public sources with the
error:

ERROR: full-1.0-r0 do_rootfs: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:license_create_manifest(d)
     0003:
File: '(...)/poky/meta/classes/license_image.bbclass', lineno: 47, function: license_create_manifest
     0043:            pkg_dic[pkg_name]["LICENSE"] = pkg_dic[pkg_name][pkg_lic_name]
     0044:
     0045:    rootfs_license_manifest = os.path.join(d.getVar('LICENSE_DIRECTORY'),
     0046:                        d.getVar('IMAGE_NAME'), 'license.manifest')
 *** 0047:    write_license_files(d, rootfs_license_manifest, pkg_dic, rootfs=True)
     0048:}
     0049:
     0050:def write_license_files(d, license_manifest, pkg_dic, rootfs=True):
     0051:    import re
File: '(...)/poky/meta/classes/license_image.bbclass', lineno: 133, function: write_license_files
     0129:
     0130:                pkg_manifest_licenses = [canonical_license(d, lic) \
     0131:                        for lic in pkg_dic[pkg]["LICENSES"]]
     0132:
 *** 0133:                licenses = os.listdir(pkg_license_dir)
     0134:                for lic in licenses:
     0135:                    pkg_license = os.path.join(pkg_license_dir, lic)
     0136:                    pkg_rootfs_license = os.path.join(pkg_rootfs_license_dir, lic)
     0137:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '(...)/deploy/licenses/ofdpa'

ERROR: Logfile of failure stored in: (...)/work/generic_x86_64-poky-linux/full/1.0-r0/temp/log.do_rootfs.2179118
ERROR: Task ((...)/poky/meta-bisdn-linux/recipes-core/images/full.bb:do_rootfs) failed with exit code '1'

So disable license inclusion again for now.

This reverts commit bebcf89620382215024cee9cf890c6e56feecf73.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>