libnl: switch to main branch to fix build
Libnl seems to have moved from master to main, with replacing master
with a very old revision(?). So point to main to make it build again.

Fixes the following error:

WARNING: libnl-1_3.5.0-r4 do_fetch: Failed to fetch URL git://github.com/thom311/libnl.git;protocol=https, attempting MIRRORS if available
ERROR: libnl-1_3.5.0-r4 do_fetch: Fetcher failure: Unable to find revision 7b167ef85f6eb4d7faca349302478b2dc121e309 in branch master even from upstream
ERROR: libnl-1_3.5.0-r4 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/thom311/libnl.git;protocol=https')
ERROR: Logfile of failure stored in: /tmp/master/work/cortexa9-vfp-poky-linux-gnueabi/libnl/1_3.5.0-r4/temp/log.do_fetch.45463
ERROR: Task (/home/ubuntu/bisdn-linux/master/poky/meta-switch/recipes-support/libnl/libnl_3.5.0.bb:do_fetch) failed with exit code '1'

No functional changes, so no PR bump needed.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>