Revert "images: do not create more filesystems than needed"
This breaks the build on ag5648 with the following error message:

ERROR: Task do_bootimg in /home/jonas/ag5648/meta-switch/recipes-core/images/full.bb depends upon non-existent task do_image_ext4 in /home/jonas/ag5648/meta-switch/recipes-core/images/full.bb
ERROR: Command execution failed: 1

So revert it until we can find the reason for the failure.

This reverts commit fe6867931459681b01867a272ab99478a99ea895.