distro: set PREFERRED_PROVIDER for docker to docker-moby
We can't just replace docker-ce with docker-moby, we also need to
override the preferred provider to make the change effective.

Fixes the following build error:

ERROR: Nothing RPROVIDES 'docker-moby' (but meta-bisdn-linux/recipes-core/images/full.bb RDEPENDS on or otherwise requires it)
docker-moby was skipped: PREFERRED_PROVIDER_virtual/docker set to docker-ce, not docker-moby
ERROR: Required build target 'full' has no buildable providers.

Fixes: 12eda9946056 ("full: replace docker-ce with docker-moby")
Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>